fix(helm): Use client version all the time as server response may be unavailable on v2 In V2 there are two versions, client and server and server version can lead to errors
Client: v2.13.0-rc.2+gb0d4c9e
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp [::1]:8080: connect: connection refused

so we stick to client only version
$ helm version -c --short
Client: v2.13.0-rc.2+gb0d4c9e

$ helm version -c --short
v3.0.0+ge29ce2a

Fixes https://github.com/eclipse/che/issues/15340

Change-Id: I0ca8ca68019aac5508079dc88f78aeff5cbdc142
Signed-off-by: Florent Benoit <fbenoit@redhat.com>